# Generated by Django 5.1.2 on 2024-11-22 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_remove_driver_hire_date_driver_hired_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='license_number',
            field=models.BigIntegerField(),
        ),
    ]
