# Generated by Django 5.1.2 on 2024-11-29 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0003_alter_driver_license_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
