# Generated by Django 5.1.2 on 2024-10-24 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='vehicle',
            table='vehicles_table',
        ),
    ]
