# Generated by Django 5.1.2 on 2024-10-25 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_remove_driver_hire_date_driver_hired_at_and_more'),
        ('vehicles', '0002_alter_vehicle_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='driven_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='drivers.driver'),
        ),
    ]
