# Generated by Django 5.1.2 on 2024-10-29 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_vehicle_driven_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='driven_by',
        ),
    ]
